name: Intersmash Applications - Simple build workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-build-wildfly:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run:  mvn -version ; mvn clean install --batch-mode

  simple-build-eap:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run:  mvn -version ; mvn clean install --batch-mode -Pwildfly-target-distribution.jboss-eap
        env:
          # JBoss EAP/Xp needs this environment variable when the Galleon "datasources" feature pack is used,
          # see https://github.com/jbossas/eap-datasources-galleon-pack/blob/main/doc/postgresql/README.md#required-configuration
          POSTGRESQL_DRIVER_VERSION: "42.7.7"

  simple-build-eap-xp:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run:  mvn -version ; mvn clean install --batch-mode -Pwildfly-target-distribution.jboss-eap-xp
        env:
          # JBoss EAP/Xp needs this environment variable when the Galleon "datasources" feature pack is used,
          # see https://github.com/jbossas/eap-datasources-galleon-pack/blob/main/doc/postgresql/README.md#required-configuration
          POSTGRESQL_DRIVER_VERSION: "42.7.7"
